ru = {
    "toggleUsePageAnim": "Использовать анимацию перехода (экспериментально)",
    "Language": "Язык",
    "javaV": "Версия java",
    "Advanced": "Дополнительно",
    "General": "Общие",
    "Back": "Назад",
    "saveLogsToFile": "Сохранить логи в файл",
    "saveLogsMsg": "Файл успешно сохранен!",
    "saveErrLogsMsg": "Не удалось сохранить файл",
    "applyNotSaved": "Применить (не сохранено)",
    "applySaved": "Применить (сохранено)",
    "nicknameInGame": "Никнейм",
    "nicknameLongError": "Никнейм слишком короткий, придумайте что-нибудь подлинее!",
    "profileTitle1": "В настоящее время лаунчер использует так называемый \"офлайн-аккаунт\"!"
                      "\nДля установки скина необходимо использовать мод, например, offlineSkins или аналогичные модули"
                      " других лаунчеров, таких как tl_skin_and_cape (TLauncher).",
    "profileTitle2": "Не рекомендуется изменять эти параметры, если вы не знаете, для чего они нужны!",
    "MoreProfile": "Подробнее",
    "showConsole": "Показывать консоль",
    "Mods": "Моды",
    "createBuild": "Создать сборку",
    "Cores": "Ядра",
    "Refresh": "Обновить",
    "Play": "Играть",
    "coreType": "Тип ядра",
    "coreVersion": "Версия ядра",
    "mineVersion": "Версия майнкрафт",
    "openFolder": "Открыть папку",
    "openBuildFolder": "Открыть папку сборки",
    "profileBtn": " Профиль ",
    "newsBtn": " Новости  ",
    "versionsBtn": "  Версии",
    "settingsBtn": "Настройки",
    "javaSettingsHelp": "Выбор java не проверяется лаунчером и выбор стоит только за вами!"
                        "\nЕсли не правильно выберете java то возникнет ошибка!",
    "SelectView": "Обзор",
    "memoryHelp": "Выделение оперативной памяти, стоит отметить, что сборки могут требовать больше, чем ванильные клиенты!"
                  "\nУказывается память в Мб.",
    "GameSettings": "Игровое",
    "youAlsoTerminate": "Вы действительно хотите принудительно закрыть игру?",
    "Terminate": "Завершить",
    "Yes": "Да",
    "No": "Нет",
    "closeUiToggle": "Скрывать лаунчер при запуске игры.",
    "Hide": "Скрыть",
    "Close": "Закрыть",
    "whenCloseCloseAll": "Скрыть — скроет окно лаунчера."
                         "\nЗакрыть — закроет все запущенные сборки вместе с лаунчером!",
    "aboutInfo": (
            "Программа: Minecraft Launcher\n"
            "Версия: {version}\n"
            "Разработчик: {author}\n"
            "Описание: Это пользовательский лаунчер для Minecraft, обеспечивающий удобный запуск игры "
            "и настройку параметров."
        ),
    "About": "О программе",
    "NoSelectProfileErr": "Не выбран профиль!",
    "useThisProfile": "Использовать этот профиль.",
    "createNewProfile": "Создать профиль",
    "deleteSelectProfile": "Удалить выбранный профиль",
    "saveAll": "Сохранить все",
    "NetworkLoading": "Сетевая загрузка",
    "Loaded": "Загружено",
    "GameVersionFilter": "Фильтр версии майнкрафт...",
    "CoreVersionFilter": "Фильтр версии ядра...",
    "SelectCoreVersion": "Выберите версию ядра для просмотра сведений о ядре",
    "Install": "Установить",
    "BuildName": "Название сборки",
    "Cancel": "Отмена",
    "Create": "Создать",
    "nameTooShort": "Название должно быть длиннее 5 символов!",
    "buildExists": "Сборка с таким названием уже существует!",
    "specifyMinecraftVersion": "Укажите версию Minecraft, которую хотите установить!",
    "Delete": "Удалить",
    "confirmDeleteBuild": "Вы правда хотите удалить сборку?",
    "buildRunning": "Сборка уже запущена!",
    "createShortcut": "Создать ярлык",
    "selectBuild": "Выберите сборку Minecraft для создания ярлыка",
    "selectIcoFile": "Выберите файл иконки",
    "noBuildSelected": "Сборка не выбрана.",
    "notAlltarnateStart": "Параллельный запуск пока не доступен!",
    "finishingUpdate": "Завершаю обновление...",
    "finishedUpdate": "Обновление завершено!",
    "showJavaConsole": "Показать java консоль",
    "checkUpdates": "Обновления",
    "updateAvailable": "Доступно обновление! Хотите обновиться до версии {version}?",
    "noUpdateAvailable": "У вас установлена последняя версия!",
    "Update": "Обновить",
    "toggleSetCheckUpdate": "Проверять обновления приложения автоматически",
}

en = {
    "toggleUsePageAnim": "Use transition animation (experimental)",
    "Language": "Language",
    "javaV": "Java version",
    "Advanced": "Advanced",
    "General": "General",
    "Back": "Back",
    "saveLogsToFile": "Save logs to file",
    "saveLogsMsg": "Logs have been saved!",
    "saveErrLogsMsg": "Failed to save logs",
    "applyNotSaved": "Apply (not saved)",
    "applySaved": "Apply (saved)",
    "nicknameInGame": "Nickname",
    "nicknameLongError": "The nickname is too short, come up with something longer!",
    "profileTitle1": "At the moment, the launcher uses an \"offline account\"!"
                            "\nTo install the skin, you need to use a mod, for example, offlineSkins or similar"
                            " modules from other launchers, such as tl_skin_and_cape (TLauncher).",
    "profileTitle2": "It is not recommended to change these parameters if you do not know what they are for!",
    "MoreProfile": "More details",
    "showConsole": "Show console",
    "Mods": "Mods",
    "createBuild": "Create build",
    "Cores": "Cores",
    "Refresh": "Refresh",
    "Play": "Play",
    "coreType": "Core type",
    "coreVersion": "Core version",
    "mineVersion": "Minecraft version",
    "openFolder": "Open folder",
    "openBuildFolder": "Open build folder",
    "profileBtn": "      Profile ",
    "newsBtn": "      News   ",
    "versionsBtn": "    Versions",
    "settingsBtn": "    Settings",
    "javaSettingsHelp": "The launcher does not verify the selected Java version, so the choice is up to you!"
                        "\nIf you choose the wrong Java version, an error will occur!",
    "SelectView": "Review",
    "memoryHelp": "RAM allocation, it's worth noting that builds may require more than vanilla clients!"
                  "\nThe memory is specified in MB.",
    "GameSettings": "Game Settings",
    "youAlsoTerminate": "Are you sure you want to force-close the game?",
    "Terminate": "Terminate",
    "Yes": "Yes",
    "No": "No",
    "closeUiToggle": "Hide the launcher when starting the game.",
    "Hide": "Hide",
    "Close": "Close",
    "whenCloseCloseAll": "Hide - It will hide the launcher window."
                         "\nClose - all running builds will be closed along with the launcher!",
    "aboutInfo": (
            "Program: Minecraft Launcher\n"
            "Version: {version}\n"
            "Developer: {author}\n"
            "Description: This is a custom launcher for Minecraft that provides a convenient way to launch the game "
            "and adjust settings."
        ),
    "About": "About",
    "NoSelectProfileErr": "The profile is not selected!",
    "useThisProfile": "Use this profile.",
    "createNewProfile": "Create profile",
    "deleteSelectProfile": "Delete selected profile",
    "saveAll": "Save all",
    "NetworkLoading": "Network Loading",
    "Loaded": "Loaded",
    "GameVersionFilter": "Game version filter...",
    "CoreVersionFilter": "Core version filter...",
    "SelectCoreVersion": "Select a core version to view details",
    "Install": "Install",
    "BuildName": "Build name",
    "Cancel": "Cancel",
    "Create": "Create",
    "nameTooShort": "The name must be longer than 5 characters!",
    "buildExists": "A build with that name already exists!",
    "specifyMinecraftVersion": "Specify the Minecraft version you want to install!",
    "Delete": "Delete",
    "confirmDeleteBuild": "Are you sure you want to delete the build?",
    "buildRunning": "Build is now running!",
    "createShortcut": "Create shortcut",
    "selectBuild": "Select a Minecraft build to create a shortcut",
    "selectIcoFile": "Select an icon file",
    "noBuildSelected": "No selected build.",
    "notAlltarnateStart": "Parallel launch is not available yet!",
    "shortcutCreateDesktop": "The shortcut has been successfully created on the desktop!",
    "shortcutCreateBuild": "The shortcut has been successfully created in the build folder!",
    "finishingUpdate": "Finishing update...",
    "finishedUpdate": "Update completed!",
    "showJavaConsole": "Show Java Console",
    "checkUpdates": "Get update`s",
    "updateAvailable": "An update is available! Do you want to update to version {version}?",
    "noUpdateAvailable": "You have the latest version installed!",
    "Update": "Update",
    "toggleSetCheckUpdate": "Check for application updates automatically",
}